#!/bin/zsh

# For instant markdown
npm install -g instant-markdown-d && gem install pygments.rb || echo "Error: Instant Markdown"

### Syntastic
# Shell
sudo apt-get install -y shellcheck || echo "Error: Shellcheck"

# JS, CSS, JSON
npm install -g jshint || echo "Error: jshint"
npm install -g csslint || echo "Error: csslint"
npm install -g jsonlint || echo "Error: jsonlint"
